# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af147556a54c523241d35c7bcfcbefead363dab9da4c88d3949370e17991c6a3351b18cefd58ccc705bb875e2fcf79ecdb42f56944695329f7d980227ec797b7

test:
  secret_key_base: 21fdfa61bd895fc95da5d3a13714dc411ab2c442864d78570aeeccb98b833eaa7d20be9fc0cab37f2fcbe1af47639d1a6db62d0cd10a8c40dea883e494174f5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
